import { RouteRecordRaw } from 'vue-router';

export const saRoutes: Array<RouteRecordRaw> = [
	{
		path: '/sa',
		name: 'Sa',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/sa/cust/main',
		meta: {
			title: 'CRM',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin'],
			icon: 'ele-Compass',
		},
		children: [
			{
				path: '/sa/proj',
				name: 'SaProj',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/sa/proj/main',
				meta: {
					title: '项目管理',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Postcard',
				},
				children: [
					{
						path: '/sa/proj/main',
						name: 'SaProjMain',
						component: () => import('/@/pages/sa/proj/main/index.vue'),
						meta: {
							title: '项目清单',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sa/proj/main/edit',
						name: 'SaProjMainEdit',
						component: () => import('/@/pages/sa/proj/main/edit.vue'),
						meta: {
							title: '项目编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sa/proj/main/view',
						name: 'SaProjMainView',
						component: () => import('/@/pages/sa/proj/main/view.vue'),
						meta: {
							title: '项目查看',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sa/prod/main',
						name: 'SaProdMain',
						component: () => import('/@/pages/sa/prod/main/index.vue'),
						meta: {
							title: '产品清单',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
				],
			},
			{
				path: '/sa/agent',
				name: 'SaAgent',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/sa/agent/main',
				meta: {
					title: '代理商管理',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Postcard',
				},
				children: [
					{
						path: '/sa/agent/cate',
						name: 'SaAgentCate',
						component: () => import('/@/pages/sa/agent/cate/index.vue'),
						meta: {
							title: '代理商分类',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sa/agent/main',
						name: 'SaAgentMain',
						component: () => import('/@/pages/sa/agent/main/index.vue'),
						meta: {
							title: '代理商清单',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sa/agent/main/edit',
						name: 'SaAgentMainEdit',
						component: () => import('/@/pages/sa/agent/main/edit.vue'),
						meta: {
							title: '代理商编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
				],
			},
			{
				path: '/sa/cust',
				name: 'SaCust',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/sa/cust/main',
				meta: {
					title: '客户管理',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Postcard',
				},
				children: [
					{
						path: '/sa/cust/cate',
						name: 'SaCustCate',
						component: () => import('/@/pages/sa/cust/cate/index.vue'),
						meta: {
							title: '客户分类',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sa/cust/main',
						name: 'SaCustMain',
						component: () => import('/@/pages/sa/cust/main/index.vue'),
						meta: {
							title: '客户清单',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sa/cust/main/edit',
						name: 'SaCustMainEdit',
						component: () => import('/@/pages/sa/cust/main/edit.vue'),
						meta: {
							title: '客户编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
				],
			},
		],
	},
];

