import { RouteRecordRaw } from 'vue-router';

export const saRoutes: Array<RouteRecordRaw> = [
    {
        path: '/sa',
        name: 'Sa',
        component: () => import('/@/layout/routerView/parent.vue'),
        redirect: '/sa/cust/main',
        meta: {
            title: '营销管理',
            isLink: '',
            isHide: false,
            isKeepAlive: true,
            isAffix: false,
            isIframe: false,
            roles: ['admin'],
            icon: 'ele-Menu',
        },
        children: [
            {
                path: '/sa/proj',
                name: 'SaProj',
                component: () => import('/@/layout/routerView/parent.vue'),
                redirect: '/sa/proj/main',
                meta: {
                    title: '项目管理',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Postcard',
                },
                children: [
                    {
                        path: '/sa/proj/cate',
                        name: 'SaProjCate',
                        component: () => import('/@/pages/sa/proj/cate/index.vue'),
                        meta: {
                            title: '项目分类',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sa/proj/cate/edit',
                        name: 'SaProjCateEdit',
                        component: () => import('/@/pages/sa/proj/cate/edit.vue'),
                        meta: {
                            title: '项目分类编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sa/proj/main',
                        name: 'SaProjMain',
                        component: () => import('/@/pages/sa/proj/main/index.vue'),
                        meta: {
                            title: '项目清单',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sa/proj/main/edit',
                        name: 'SaProjMainEdit',
                        component: () => import('/@/pages/sa/proj/main/edit.vue'),
                        meta: {
                            title: '项目编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sa/proj/main/view',
                        name: 'SaProjMainView',
                        component: () => import('/@/pages/sa/proj/main/view.vue'),
                        meta: {
                            title: '项目查看',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sa/prod/sche',
                        name: 'SaProdSche',
                        component: () => import('/@/pages/sa/prod/sche/index.vue'),
                        meta: {
                            title: '产品方案',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    // {
                    //     path: '/sa/prod/main',
                    //     name: 'SaProdMain',
                    //     component: () => import('/@/pages/sa/prod/main/index.vue'),
                    //     meta: {
                    //         title: '产品清单',
                    //         isLink: '',
                    //         isHide: true,
                    //         isKeepAlive: true,
                    //         isAffix: false,
                    //         isIframe: false,
                    //         roles: ['admin'],
                    //         icon: 'ele-Tickets',
                    //     },
                    // },
                ],
            },
            {
                path: '/sa/draw',
                name: 'SaDraw',
                component: () => import('/@/layout/routerView/parent.vue'),
                redirect: '/sa/draw/main',
                meta: {
                    title: '出图管理',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Postcard',
                },
                children: [
                    {
                        path: '/sa/draw/cate',
                        name: 'SaDrawCate',
                        component: () => import('/@/pages/sa/draw/cate/index.vue'),
                        meta: {
                            title: '出图分类',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sa/draw/cate/edit',
                        name: 'SaDrawCateEdit',
                        component: () => import('/@/pages/sa/draw/cate/edit.vue'),
                        meta: {
                            title: '出图分类编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sa/draw/main',
                        name: 'SaDrawMain',
                        component: () => import('/@/pages/sa/draw/main/index.vue'),
                        meta: {
                            title: '土建出图',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sa/draw/main/view',
                        name: 'SaDrawMainView',
                        component: () => import('/@/pages/sa/draw/main/view.vue'),
                        meta: {
                            title: '出图查看',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sa/draw/main/edit',
                        name: 'SaDrawMainEdit',
                        component: () => import('/@/pages/sa/draw/main/edit.vue'),
                        meta: {
                            title: '出图编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                ],
            },
            // {
            //     path: '/sa/dist',
            //     name: 'SaDist',
            //     component: () => import('/@/layout/routerView/parent.vue'),
            //     redirect: '/sa/dist/main',
            //     meta: {
            //         title: '渠道管理',
            //         isLink: '',
            //         isHide: false,
            //         isKeepAlive: true,
            //         isAffix: false,
            //         isIframe: false,
            //         roles: ['admin'],
            //         icon: 'ele-Postcard',
            //     },
            //     children: [
            //         {
            //             path: '/sa/dist/form',
            //             name: 'SaDistForm',
            //             component: () => import('/@/pages/sa/dist/form/index.vue'),
            //             meta: {
            //                 title: '表单配置',
            //                 isLink: '',
            //                 isHide: false,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //         {
            //             path: '/sa/dist/proc',
            //             name: 'SaDistProc',
            //             component: () => import('/@/pages/sa/dist/proc/index.vue'),
            //             meta: {
            //                 title: '流程配置',
            //                 isLink: '',
            //                 isHide: false,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //         {
            //             path: '/sa/dist/cate',
            //             name: 'SaDistCate',
            //             component: () => import('/@/pages/sa/dist/cate/index.vue'),
            //             meta: {
            //                 title: '分类配置',
            //                 isLink: '',
            //                 isHide: false,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //         {
            //             path: '/sa/dist/cate/edit',
            //             name: 'SaDistCateEdit',
            //             component: () => import('/@/pages/sa/dist/cate/edit.vue'),
            //             meta: {
            //                 title: '代理商分类配置',
            //                 isLink: '',
            //                 isHide: true,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //         {
            //             path: '/sa/dist/main',
            //             name: 'SaDistMain',
            //             component: () => import('/@/pages/sa/dist/main/index.vue'),
            //             meta: {
            //                 title: '代理商清单',
            //                 isLink: '',
            //                 isHide: false,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //         {
            //             path: '/sa/dist/main/edit',
            //             name: 'SaDistMainEdit',
            //             component: () => import('/@/pages/sa/dist/main/edit.vue'),
            //             meta: {
            //                 title: '代理商编辑',
            //                 isLink: '',
            //                 isHide: true,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //         {
            //             path: '/sa/dist/main/view',
            //             name: 'SaDistMainView',
            //             component: () => import('/@/pages/sa/dist/main/view.vue'),
            //             meta: {
            //                 title: '代理商查看',
            //                 isLink: '',
            //                 isHide: true,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //         {
            //             path: '/sa/dist/main/edit2',
            //             name: 'SaDistMainEdit2',
            //             component: () => import('/@/pages/sa/dist/main/edit2.vue'),
            //             meta: {
            //                 title: '代理商编辑',
            //                 isLink: '',
            //                 isHide: true,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //         {
            //             path: '/sa/dist/main/view2',
            //             name: 'SaDistMainView2',
            //             component: () => import('/@/pages/sa/dist/main/view2.vue'),
            //             meta: {
            //                 title: '代理商查看',
            //                 isLink: '',
            //                 isHide: true,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //     ],
            // },
            // {
            //     path: '/sa/cust',
            //     name: 'SaCust',
            //     component: () => import('/@/layout/routerView/parent.vue'),
            //     redirect: '/sa/cust/main',
            //     meta: {
            //         title: '客户管理',
            //         isLink: '',
            //         isHide: false,
            //         isKeepAlive: true,
            //         isAffix: false,
            //         isIframe: false,
            //         roles: ['admin'],
            //         icon: 'ele-Postcard',
            //     },
            //     children: [
            //         {
            //             path: '/sa/cust/cate',
            //             name: 'SaCustCate',
            //             component: () => import('/@/pages/sa/cust/cate/index.vue'),
            //             meta: {
            //                 title: '客户分类',
            //                 isLink: '',
            //                 isHide: false,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //         {
            //             path: '/sa/cust/cate/edit',
            //             name: 'SaCustCateEdit',
            //             component: () => import('/@/pages/sa/cust/cate/edit.vue'),
            //             meta: {
            //                 title: '客户分类编辑',
            //                 isLink: '',
            //                 isHide: true,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //         {
            //             path: '/sa/cust/main',
            //             name: 'SaCustMain',
            //             component: () => import('/@/pages/sa/cust/main/index.vue'),
            //             meta: {
            //                 title: '客户清单',
            //                 isLink: '',
            //                 isHide: false,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //         {
            //             path: '/sa/cust/main/edit',
            //             name: 'SaCustMainEdit',
            //             component: () => import('/@/pages/sa/cust/main/edit.vue'),
            //             meta: {
            //                 title: '客户编辑',
            //                 isLink: '',
            //                 isHide: true,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //     ],
            // },
            // {
            //     path: '/sa/file',
            //     name: 'SaFile',
            //     component: () => import('/@/layout/routerView/parent.vue'),
            //     redirect: '/sa/file/comp',
            //     meta: {
            //         title: '文件管理',
            //         isLink: '',
            //         isHide: false,
            //         isKeepAlive: true,
            //         isAffix: false,
            //         isIframe: false,
            //         roles: ['admin'],
            //         icon: 'ele-Postcard',
            //     },
            //     children: [
            //         {
            //             path: '/sa/file/comp',
            //             name: 'SaFileComp',
            //             component: () => import('/@/pages/sa/file/comp/index.vue'),
            //             meta: {
            //                 title: '文件组件',
            //                 isLink: '',
            //                 isHide: false,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //         {
            //             path: '/sa/file/comp/edit',
            //             name: 'SaFileCompEdit',
            //             component: () => import('/@/pages/sa/file/comp/edit.vue'),
            //             meta: {
            //                 title: '文件组件编辑',
            //                 isLink: '',
            //                 isHide: true,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //         {
            //             path: '/sa/file/temp',
            //             name: 'SaFileTemp',
            //             component: () => import('/@/pages/sa/file/temp/index.vue'),
            //             meta: {
            //                 title: '文件模板',
            //                 isLink: '',
            //                 isHide: false,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //         {
            //             path: '/sa/file/temp/edit',
            //             name: 'SaFileTempEdit',
            //             component: () => import('/@/pages/sa/file/temp/edit.vue'),
            //             meta: {
            //                 title: '文件模板编辑',
            //                 isLink: '',
            //                 isHide: true,
            //                 isKeepAlive: true,
            //                 isAffix: false,
            //                 isIframe: false,
            //                 roles: ['admin'],
            //                 icon: 'ele-Tickets',
            //             },
            //         },
            //     ],
            // },
            {
                path: '/sa/org',
                name: 'SaOrg',
                component: () => import('/@/layout/routerView/parent.vue'),
                redirect: '/sa/org/branch',
                meta: {
                    title: '销售组织',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Postcard',
                },
                children: [
                    {
                        path: '/sa/org/branch',
                        name: 'SaOrgBranch',
                        component: () => import('/@/pages/sa/org/branch/index.vue'),
                        meta: {
                            title: '销售机构',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sa/org/branch/edit',
                        name: 'SaOrgBranchEdit',
                        component: () => import('/@/pages/sa/org/branch/edit.vue'),
                        meta: {
                            title: '销售机构编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sa/org/team',
                        name: 'SaOrgTeam',
                        component: () => import('/@/pages/sa/org/team/index.vue'),
                        meta: {
                            title: '销售小组',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sa/org/team/edit',
                        name: 'SaOrgTeamEdit',
                        component: () => import('/@/pages/sa/org/team/edit.vue'),
                        meta: {
                            title: '销售小组编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sa/org/man',
                        name: 'SaOrgMan',
                        component: () => import('/@/pages/sa/org/man/index.vue'),
                        meta: {
                            title: '销售人员',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sa/org/man/edit',
                        name: 'SaOrgManEdit',
                        component: () => import('/@/pages/sa/org/man/edit.vue'),
                        meta: {
                            title: '销售人员编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                ],
            },
        ],
    },
];

