import { RouteRecordRaw } from 'vue-router';

export const saRoutes: Array<RouteRecordRaw> = [
	{
		path: '/te/prod',
		name: 'teProd',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/te/prod/model',
		meta: {
			title: '产品管理',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin'],
			icon: 'iconfont icon-xitongshezhi',
		},
		children: [
			{
				path: '/te/prod/cate',
				name: 'teProdCate',
				component: () => import('/@/pages/te/prod/cate/index.vue'),
				meta: {
					title: '产品分类',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/prod/serie',
				name: 'teProdSerie',
				component: () => import('/@/pages/te/prod/serie/index.vue'),
				meta: {
					title: '产品系列',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/prod/model',
				name: 'teProdModel',
				component: () => import('/@/pages/te/prod/model/index.vue'),
				meta: {
					title: '产品型号',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/prod/version',
				name: 'teProdVersion',
				component: () => import('/@/pages/te/prod/version/index.vue'),
				meta: {
					title: '产品版本',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/prod/version/edit',
				name: 'teProdVersionEdit',
				component: () => import('/@/pages/te/prod/version/edit.vue'),
				meta: {
					title: '产品版本编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/prod/test',
				name: 'teProdTest',
				component: () => import('/@/pages/te/prod/test/index.vue'),
				meta: {
					title: '产品测试',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/prod/test/edit',
				name: 'teProdTestEdit',
				component: () => import('/@/pages/te/prod/test/edit.vue'),
				meta: {
					title: '产品测试编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
		],
	},
	{
		path: '/te/feat',
		name: 'teFeat',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/te/feat/param',
		meta: {
			title: '特性管理',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin'],
			icon: 'iconfont icon-xitongshezhi',
		},
		children: [
			{
				path: '/te/feat/screen',
				name: 'teFeatScreen',
				component: () => import('/@/pages/te/feat/screen/index.vue'),
				meta: {
					title: '特性屏幕',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/feat/param',
				name: 'teFeatParam',
				component: () => import('/@/pages/te/feat/param/index.vue'),
				meta: {
					title: '特性参数',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/feat/param/edit',
				name: 'teFeatParamEdit',
				component: () => import('/@/pages/te/feat/param/edit.vue'),
				meta: {
					title: '参数编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Comment',
				},
			},
			{
				path: '/te/feat/link',
				name: 'teFeatLink',
				component: () => import('/@/pages/te/feat/link/index.vue'),
				meta: {
					title: '特性联动',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/feat/link/edit',
				name: 'teFeatLinkEdit',
				component: () => import('/@/pages/te/feat/link/edit.vue'),
				meta: {
					title: '联动编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/feat/check',
				name: 'teFeatCheck',
				component: () => import('/@/pages/te/feat/check/index.vue'),
				meta: {
					title: '特性校验',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/feat/check/edit',
				name: 'teFeatCheckEdit',
				component: () => import('/@/pages/te/feat/check/edit.vue'),
				meta: {
					title: '校验编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/feat/drive',
				name: 'teFeatDrive',
				component: () => import('/@/pages/te/feat/drive/index.vue'),
				meta: {
					title: '特性驱动',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/feat/drive/edit',
				name: 'teFeatDriveEdit',
				component: () => import('/@/pages/te/feat/drive/edit.vue'),
				meta: {
					title: '驱动编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			// {
			// 	path: '/te/feat/comp',
			// 	name: 'teFeatComp',
			// 	component: () => import('/@/pages/te/feat/comp/index.vue'),
			// 	meta: {
			// 		title: '特性组件',
			// 		isLink: '',
			// 		isHide: false,
			// 		isKeepAlive: true,
			// 		isAffix: false,
			// 		isIframe: false,
			// 		roles: ['admin'],
			// 		icon: 'iconfont icon-caidan',
			// 	},
			// },
			// {
			// 	path: '/te/feat/comp/edit',
			// 	name: 'teFeatCompEdit',
			// 	component: () => import('/@/pages/te/feat/comp/edit.vue'),
			// 	meta: {
			// 		title: '组件编辑',
			// 		isLink: '',
			// 		isHide: true,
			// 		isKeepAlive: true,
			// 		isAffix: false,
			// 		isIframe: false,
			// 		roles: ['admin'],
			// 		icon: 'iconfont icon-caidan',
			// 	},
			// },
		],
	},
	{
		path: '/te/allot',
		name: 'teAllot',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/te/allot/param',
		meta: {
			title: '分配管理',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin'],
			icon: 'iconfont icon-xitongshezhi',
		},
		children: [
			{
				path: '/te/allot/param',
				name: 'teAllotParam',
				component: () => import('/@/pages/te/allot/param/index.vue'),
				meta: {
					title: '参数分配',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/allot/param/edit',
				name: 'teAllotParamEdit',
				component: () => import('/@/pages/te/allot/param/edit.vue'),
				meta: {
					title: '参数分配编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Comment',
				},
			},
			{
				path: '/te/allot/link',
				name: 'teAllotLink',
				component: () => import('/@/pages/te/allot/link/index.vue'),
				meta: {
					title: '联动分配',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/allot/link/edit',
				name: 'teAllotLinkEdit',
				component: () => import('/@/pages/te/allot/link/edit.vue'),
				meta: {
					title: '联动分配编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Comment',
				},
			},
			{
				path: '/te/allot/check',
				name: 'teAllotCheck',
				component: () => import('/@/pages/te/allot/check/index.vue'),
				meta: {
					title: '校验分配',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/allot/check/edit',
				name: 'teAllotCheckEdit',
				component: () => import('/@/pages/te/allot/check/edit.vue'),
				meta: {
					title: '校验分配编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Comment',
				},
			},
			{
				path: '/te/allot/drive',
				name: 'teAllotDrive',
				component: () => import('/@/pages/te/allot/drive/index.vue'),
				meta: {
					title: '驱动分配',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/allot/drive/edit',
				name: 'teAllotDriveEdit',
				component: () => import('/@/pages/te/allot/drive/edit.vue'),
				meta: {
					title: '驱动分配编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Comment',
				},
			},
		],
	},
	{
		path: '/te/tran',
		name: 'teTran',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/te/tran/main',
		meta: {
			title: '转换管理',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin'],
			icon: 'iconfont icon-xitongshezhi',
		},
		children: [
			{
				path: '/te/tran/cate',
				name: 'teTranCate',
				component: () => import('/@/pages/te/tran/cate/index.vue'),
				meta: {
					title: '转换分类',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/tran/main',
				name: 'teTranMain',
				component: () => import('/@/pages/te/tran/main/index.vue'),
				meta: {
					title: '转换映射',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
			{
				path: '/te/tran/main/edit',
				name: 'teTranMainEdit',
				component: () => import('/@/pages/te/tran/main/edit.vue'),
				meta: {
					title: '转换编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'iconfont icon-caidan',
				},
			},
		],
	},
];

