import {RouteRecordRaw} from 'vue-router';

export const sysRoutes: Array<RouteRecordRaw> = [
    {
        path: '/sys',
        name: 'Sys',
        component: () => import('/@/layout/routerView/parent.vue'),
        redirect: '/sys/org/user',
        meta: {
            title: '系统管理',
            isLink: '',
            isHide: false,
            isKeepAlive: true,
            isAffix: false,
            isIframe: false,
            roles: ['admin', 'common'],
            icon: 'iconfont icon-xitongshezhi',
        },
        children: [
            {
                path: '/sys/org',
                name: 'SysOrg',
                component: () => import('/@/layout/routerView/parent.vue'),
                redirect: '/sys/org/user',
                meta: {
                    title: '组织架构',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin', 'common'],
                    icon: 'ele-OfficeBuilding',
                },
                children: [
                    {
                        path: '/sys/org/dept',
                        name: 'SysOrgDept',
                        component: () => import('/@/pages/sys/org/dept/index.vue'),
                        meta: {
                            title: '部门管理',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin', 'common'],
                            icon: 'ele-SetUp',
                        },
                    },
                    {
                        path: '/sys/org/dept/edit',
                        name: 'SysOrgDeptEdit',
                        component: () => import('/@/pages/sys/org/dept/edit.vue'),
                        meta: {
                            title: '部门编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'iconfont icon-caidan',
                        },
                    },
                    {
                        path: '/sys/org/user',
                        name: 'SysOrgUser',
                        component: () => import('/@/pages/sys/org/user/index.vue'),
                        meta: {
                            title: '用户管理',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-User',
                        },
                    },
                    {
                        path: '/sys/org/user/edit',
                        name: 'SysOrgUserEdit',
                        component: () => import('/@/pages/sys/org/user/edit.vue'),
                        meta: {
                            title: '用户编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'iconfont icon-caidan',
                        },
                    },
                    {
                        path: '/sys/org/post',
                        name: 'SysOrgPost',
                        component: () => import('/@/pages/sys/org/post/index.vue'),
                        meta: {
                            title: '岗位管理',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Help',
                        },
                    },
                    {
                        path: '/sys/org/post/edit',
                        name: 'SysOrgPostEdit',
                        component: () => import('/@/pages/sys/org/post/edit.vue'),
                        meta: {
                            title: '岗位编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'iconfont icon-caidan',
                        },
                    },
                    {
                        path: '/sys/org/group',
                        name: 'SysOrgGroup',
                        component: () => import('/@/pages/sys/org/group/index.vue'),
                        meta: {
                            title: '群组管理',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Guide',
                        },
                    },
                    {
                        path: '/sys/org/group/edit',
                        name: 'SysOrgGroupEdit',
                        component: () => import('/@/pages/sys/org/group/edit.vue'),
                        meta: {
                            title: '群组编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'iconfont icon-caidan',
                        },
                    },
                    {
                        path: '/sys/org/ttree',
                        name: 'SysOrgTtree',
                        component: () => import('/@/pages/sys/org/tier/tree.vue'),
                        meta: {
                            title: '层级管理',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Cherry',
                        },
                    },
                    {
                        path: '/sys/org/ttree/edit',
                        name: 'SysOrgTtreeEdit',
                        component: () => import('/@/pages/sys/org/tier/tree_edit.vue'),
                        meta: {
                            title: '层级树编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'iconfont icon-caidan',
                        },
                    },
                    {
                        path: '/sys/org/tnode',
                        name: 'SysOrgTnode',
                        component: () => import('/@/pages/sys/org/tier/node.vue'),
                        meta: {
                            title: '层级节点配置',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'iconfont icon-caidan',
                        },
                    },
                ],
            },
            {
                path: '/sys/api',
                name: 'SysApi',
                component: () => import('/@/layout/routerView/parent.vue'),
                redirect: '/sys/api/main',
                meta: {
                    title: '接口管理',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Lock',
                },
                children: [
                    {
                        path: '/sys/api/main',
                        name: 'SysApiMain',
                        component: () => import('/@/pages/sys/api/main/index.vue'),
                        meta: {
                            title: '接口清单',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sys/api/main/doc',
                        name: 'SysApiMainDoc',
                        component: () => import('/@/layout/routerView/link.vue'),
                        meta: {
                            title: '接口文档',
                            isLink: `${import.meta.env.VITE_API_URL}doc.html`,
                            isHide: false,
                            isKeepAlive: false,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'iconfont icon-caozuo-wailian',
                        },
                    },
                    {
                        path: '/sys/api/main/edit',
                        name: 'SysApiMainEdit',
                        component: () => import('/@/pages/sys/api/main/edit.vue'),
                        meta: {
                            title: '接口编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sys/api/role',
                        name: 'SysApiRole',
                        component: () => import('/@/pages/sys/api/role/index.vue'),
                        meta: {
                            title: '接口角色',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sys/api/role/edit',
                        name: 'SysApiRoleEdit',
                        component: () => import('/@/pages/sys/api/role/edit.vue'),
                        meta: {
                            title: '角色编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                        },
                    },
                ],
            },
            {
                path: '/sys/portal',
                name: 'SysPortal',
                component: () => import('/@/layout/routerView/parent.vue'),
                redirect: '/sys/portal/main',
                meta: {
                    title: '门户管理',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Notebook',
                },
                children: [
                    {
                        path: '/sys/portal/main',
                        name: 'SysPortalMain',
                        component: () => import('/@/pages/sys/portal/main/index.vue'),
                        meta: {
                            title: '门户列表',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sys/portal/main/edit',
                        name: 'SysPortalMainEdit',
                        component: () => import('/@/pages/sys/portal/main/edit.vue'),
                        meta: {
                            title: '门户编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sys/portal/menu',
                        name: 'SysPortalMenu',
                        component: () => import('/@/pages/sys/portal/menu/index.vue'),
                        meta: {
                            title: '门户菜单',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sys/portal/menu/edit',
                        name: 'SysPortalMenuEdit',
                        component: () => import('/@/pages/sys/portal/menu/edit.vue'),
                        meta: {
                            title: '菜单编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sys/portal/role',
                        name: 'SysPortalRole',
                        component: () => import('/@/pages/sys/portal/role/index.vue'),
                        meta: {
                            title: '门户角色',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/sys/portal/role/edit',
                        name: 'SysPortalRoleEdit',
                        component: () => import('/@/pages/sys/portal/role/edit.vue'),
                        meta: {
                            title: '角色编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                ],
            },
        ],
    },
    {
        path: '/mon',
        name: 'Mon',
        component: () => import('/@/layout/routerView/parent.vue'),
        redirect: '/mon/server/main',
        meta: {
            title: '监控中心',
            isLink: '',
            isHide: false,
            isKeepAlive: true,
            isAffix: false,
            isIframe: false,
            roles: ['admin'],
            icon: 'ele-DataLine',
        },
        children: [
            {
                path: '/mon/online/user',
                name: 'MonOnlineUser',
                component: () => import('/@/pages/mon/online/user/index.vue'),
                meta: {
                    title: '在线用户',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/mon/log/login',
                name: 'MonLogLogin',
                component: () => import('/@/pages/mon/log/login/index.vue'),
                meta: {
                    title: '登录日志',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/mon/log/oper',
                name: 'MonLogOper',
                component: () => import('/@/pages/mon/log/oper/index.vue'),
                meta: {
                    title: '操作日志',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/mon/log/error',
                name: 'MonLogError',
                component: () => import('/@/pages/mon/log/error/index.vue'),
                meta: {
                    title: '错误日志',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/mon/job/main',
                name: 'MonJobMain',
                component: () => import('/@/pages/mon/job/main/index.vue'),
                meta: {
                    title: '定时任务',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/mon/job/main/edit',
                name: 'MonJobMainEdit',
                component: () => import('/@/pages/mon/job/main/edit.vue'),
                meta: {
                    title: '定时任务编辑',
                    isLink: '',
                    isHide: true,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                },
            },
            {
                path: '/mon/job/log',
                name: 'MonJobLog',
                component: () => import('/@/pages/mon/job/log/index.vue'),
                meta: {
                    title: '定时任务日志',
                    isLink: '',
                    isHide: true,
                    isKeepAlive: false,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/mon/server/main',
                name: 'MonServerMain',
                component: () => import('/@/pages/mon/server/main/show.vue'),
                meta: {
                    title: '服务监控',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/mon/cache/main',
                name: 'MonCacheMain',
                component: () => import('/@/pages/mon/cache/main/show.vue'),
                meta: {
                    title: '缓存监控',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/mon/db/main',
                name: 'MonDbMain',
                component: () => import('/@/layout/routerView/link.vue'),
                meta: {
                    title: '数据监控',
                    isLink: `${import.meta.env.VITE_API_URL}druid/sql.html`,
                    isHide: false,
                    isKeepAlive: false,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
        ],
    },
    {
        path: '/ass',
        name: 'Ass',
        component: () => import('/@/layout/routerView/parent.vue'),
        redirect: '/ass/dict/main',
        meta: {
            title: '辅助工具',
            isLink: '',
            isHide: false,
            isKeepAlive: true,
            isAffix: false,
            isIframe: false,
            roles: ['admin'],
            // icon: 'ele-Help',
            icon: 'ele-Suitcase',
        },
        children: [
            {
                path: '/ass/coge/form',
                name: 'AssCogeForm',
                component: () => import('/@/pages/ass/coge/form/index.vue'),
                meta: {
                    title: '表单设计',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/ass/coge/form/edit',
                name: 'AssCogeFormEdit',
                component: () => import('/@/pages/ass/coge/form/edit.vue'),
                meta: {
                    title: '表单设计维护',
                    isLink: '',
                    isHide: true,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/ass/coge/table',
                name: 'AssCogeTable',
                component: () => import('/@/pages/ass/coge/table/index.vue'),
                meta: {
                    title: '代码生成',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/ass/coge/table/edit',
                name: 'AssCogeTableEdit',
                component: () => import('/@/pages/ass/coge/table/edit.vue'),
                meta: {
                    title: '代码生成配置',
                    isLink: '',
                    isHide: true,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/ass/dict/main',
                name: 'AssDictMain',
                component: () => import('/@/pages/ass/dict/main/index.vue'),
                meta: {
                    title: '数据字典',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/ass/dict/data',
                name: 'AssDictData',
                component: () => import('/@/pages/ass/dict/data/index.vue'),
                meta: {
                    title: '字典配置',
                    isLink: '',
                    isHide: true,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/ass/num/main',
                name: 'AssNumMain',
                component: () => import('/@/pages/ass/num/main/index.vue'),
                meta: {
                    title: '编号策略',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/ass/addr/main',
                name: 'AssAddrMain',
                component: () => import('/@/pages/ass/addr/main/index.vue'),
                meta: {
                    title: '省市区县',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
        ],
    },
    {
        path: '/oa',
        name: 'Oa',
        component: () => import('/@/layout/routerView/parent.vue'),
        redirect: '/oa/flow/main',
        meta: {
            title: '应用中心',
            isLink: '',
            isHide: false,
            isKeepAlive: true,
            isAffix: false,
            isIframe: false,
            roles: ['admin'],
            icon: 'ele-Menu',
        },
        children: [
            {
                path: '/oa/flow',
                name: 'OaFlow',
                component: () => import('/@/layout/routerView/parent.vue'),
                redirect: '/oa/flow/main',
                meta: {
                    title: '流程管理',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Connection',
                },
                children: [
                    {
                        path: '/oa/flow/cate',
                        name: 'OaFlowCate',
                        component: () => import('/@/pages/oa/flow/cate/index.vue'),
                        meta: {
                            title: '流程分类',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/oa/flow/cate/edit',
                        name: 'OaFlowCateEdit',
                        component: () => import('/@/pages/oa/flow/cate/edit.vue'),
                        meta: {
                            title: '流程分类编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/oa/flow/temp',
                        name: 'OaFlowTemp',
                        component: () => import('/@/pages/oa/flow/temp/index.vue'),
                        meta: {
                            title: '流程模板',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/oa/flow/temp/edit',
                        name: 'OaFlowTempEdit',
                        component: () => import('/@/pages/oa/flow/temp/edit.vue'),
                        meta: {
                            title: '流程模板编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/oa/flow/main',
                        name: 'OaFlowMain',
                        component: () => import('/@/pages/oa/flow/main/index.vue'),
                        meta: {
                            title: '流程实例',
                            isLink: '',
                            isHide: false,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/oa/flow/main/view',
                        name: 'OaFlowMainView',
                        component: () => import('/@/pages/oa/flow/main/view.vue'),
                        meta: {
                            title: '流程查看',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                    {
                        path: '/oa/flow/main/edit',
                        name: 'OaFlowMainEdit',
                        component: () => import('/@/pages/oa/flow/main/edit.vue'),
                        meta: {
                            title: '流程编辑',
                            isLink: '',
                            isHide: true,
                            isKeepAlive: true,
                            isAffix: false,
                            isIframe: false,
                            roles: ['admin'],
                            icon: 'ele-Tickets',
                        },
                    },
                ],
            },
        ],
    },
    // {
    // 	path: '/sys/todo',
    // 	name: 'SysTodo',
    // 	component: () => import('/@/layout/routerView/parent.vue'),
    // 	redirect: '/sys/todo/main',
    // 	meta: {
    // 		title: '待办管理',
    // 		isLink: '',
    // 		isHide: false,
    // 		isKeepAlive: true,
    // 		isAffix: false,
    // 		isIframe: false,
    // 		roles: ['admin'],
    // 		icon: 'ele-Bell',
    // 	},
    // 	children: [
    // 		{
    // 			path: '/sys/todo/main',
    // 			name: 'SysTodoMain',
    // 			component: () => import('/@/pages/sys/todo/main/index.vue'),
    // 			meta: {
    // 				title: '待办清单',
    // 				isLink: '',
    // 				isHide: false,
    // 				isKeepAlive: true,
    // 				isAffix: false,
    // 				isIframe: false,
    // 				roles: ['admin'],
    // 				icon: 'ele-Tickets',
    // 			},
    // 		},
    // 		{
    // 			path: '/sys/todo/main/edit',
    // 			name: 'SysTodoMainEdit',
    // 			component: () => import('/@/pages/sys/todo/main/edit.vue'),
    // 			meta: {
    // 				title: '待办编辑',
    // 				isLink: '',
    // 				isHide: true,
    // 				isKeepAlive: true,
    // 				isAffix: false,
    // 				isIframe: false,
    // 				roles: ['admin'],
    // 				icon: 'ele-Tickets',
    // 			},
    // 		},
    // 	],
    // },
    {
        path: '/de',
        name: 'De',
        component: () => import('/@/layout/routerView/parent.vue'),
        redirect: '/de/supp/main',
        meta: {
            title: 'DEMO',
            isLink: '',
            isHide: false,
            isKeepAlive: true,
            isAffix: false,
            isIframe: false,
            roles: ['admin'],
            icon: 'ele-GobletSquare',
        },
        children: [
            {
                path: '/de/supp/cate',
                name: 'DeSuppCate',
                component: () => import('/@/pages/de/supp/cate/index.vue'),
                meta: {
                    title: '供应商分类',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/de/supp/main',
                name: 'DeSuppMain',
                component: () => import('/@/pages/de/supp/main/index.vue'),
                meta: {
                    title: '供应商清单',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/de/supp/main/edit',
                name: 'DeSuppMainEdit',
                component: () => import('/@/pages/de/supp/main/edit.vue'),
                meta: {
                    title: '供应商编辑',
                    isLink: '',
                    isHide: true,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/de/supp/mark',
                name: 'DeSuppMark',
                component: () => import('/@/layout/routerView/iframes.vue'),
                meta: {
                    title: '供应商分布',
                    isLink: '/ass/mark.html',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: true,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/de/cust/main',
                name: 'DeCustMain',
                component: () => import('/@/pages/de/cust/main/index.vue'),
                meta: {
                    title: '客户清单',
                    isLink: '',
                    isHide: false,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
            {
                path: '/de/cust/main/edit',
                name: 'DeCustMainEdit',
                component: () => import('/@/pages/de/cust/main/edit.vue'),
                meta: {
                    title: '客户编辑',
                    isLink: '',
                    isHide: true,
                    isKeepAlive: true,
                    isAffix: false,
                    isIframe: false,
                    roles: ['admin'],
                    icon: 'ele-Tickets',
                },
            },
        ],
    },
];

