import { RouteRecordRaw } from 'vue-router';

export const sysRoutes: Array<RouteRecordRaw> = [
	{
		path: '/sys',
		name: 'Sys',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/sys/org/user',
		meta: {
			title: '系统管理',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin', 'common'],
			icon: 'ele-Setting',
		},
		children: [
			{
				path: '/sys/org',
				name: 'SysOrg',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/sys/org/user',
				meta: {
					title: '组织架构',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin', 'common'],
					icon: 'ele-OfficeBuilding',
				},
				children: [
					{
						path: '/sys/org/dept',
						name: 'SysOrgDept',
						component: () => import('/@/pages/sys/org/dept/index.vue'),
						meta: {
							title: '部门管理',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin', 'common'],
							icon: 'ele-SetUp',
						},
					},
					{
						path: '/sys/org/dept/tindex',
						name: 'SysOrgDeptTindex',
						component: () => import('/@/pages/sys/org/dept/tindex.vue'),
						meta: {
							title: '部门管理',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin', 'common'],
							icon: 'ele-SetUp',
						},
					},
					{
						path: '/sys/org/dept/edit',
						name: 'SysOrgDeptEdit',
						component: () => import('/@/pages/sys/org/dept/edit.vue'),
						meta: {
							title: '部门编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/org/user',
						name: 'SysOrgUser',
						component: () => import('/@/pages/sys/org/user/index.vue'),
						meta: {
							title: '用户管理',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-User',
						},
					},
					{
						path: '/sys/org/user/edit',
						name: 'SysOrgUserEdit',
						component: () => import('/@/pages/sys/org/user/edit.vue'),
						meta: {
							title: '用户编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/org/post',
						name: 'SysOrgPost',
						component: () => import('/@/pages/sys/org/post/index.vue'),
						meta: {
							title: '岗位管理',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Help',
						},
					},
					{
						path: '/sys/org/post/edit',
						name: 'SysOrgPostEdit',
						component: () => import('/@/pages/sys/org/post/edit.vue'),
						meta: {
							title: '岗位编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/org/group',
						name: 'SysOrgGroup',
						component: () => import('/@/pages/sys/org/group/index.vue'),
						meta: {
							title: '群组管理',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Guide',
						},
					},
					{
						path: '/sys/org/group/edit',
						name: 'SysOrgGroupEdit',
						component: () => import('/@/pages/sys/org/group/edit.vue'),
						meta: {
							title: '群组编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/org/rtree',
						name: 'SysOrgRtree',
						component: () => import('/@/pages/sys/org/role/tree.vue'),
						meta: {
							title: '角色管理',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Cherry',
						},
					},
					{
						path: '/sys/org/rtree/edit',
						name: 'SysOrgRtreeEdit',
						component: () => import('/@/pages/sys/org/role/tree_edit.vue'),
						meta: {
							title: '角色树编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/org/rnode',
						name: 'SysOrgRnode',
						component: () => import('/@/pages/sys/org/role/node.vue'),
						meta: {
							title: '角色节点配置',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
				],
			},
			{
				path: '/sys/coop',
				name: 'SysCoop',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/sys/coop/user',
				meta: {
					title: '外部协同',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin', 'common'],
					icon: 'ele-Magnet',
				},
				children: [
					{
						path: '/sys/coop/cate',
						name: 'SysCoopCate',
						component: () => import('/@/pages/sys/coop/cate/index.vue'),
						meta: {
							title: '协同分类',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/coop/corp',
						name: 'SysCoopCorp',
						component: () => import('/@/pages/sys/coop/corp/index.vue'),
						meta: {
							title: '外部公司',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/coop/user',
						name: 'SysCoopUser',
						component: () => import('/@/pages/sys/coop/user/index.vue'),
						meta: {
							title: '外部用户',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
				],
			},

			{
				path: '/sys/api',
				name: 'SysApi',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/sys/api/main',
				meta: {
					title: '接口管理',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Lock',
				},
				children: [
					{
						path: '/sys/api/main',
						name: 'SysApiMain',
						component: () => import('/@/pages/sys/api/main/index.vue'),
						meta: {
							title: '接口清单',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/api/main/doc',
						name: 'SysApiMainDoc',
						component: () => import('/@/layout/routerView/link.vue'),
						meta: {
							title: '接口文档',
							isLink: `${import.meta.env.VITE_API_URL}doc.html`,
							isHide: false,
							isKeepAlive: false,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'iconfont icon-caozuo-wailian',
						},
					},
					{
						path: '/sys/api/role',
						name: 'SysApiRole',
						component: () => import('/@/pages/sys/api/role/index.vue'),
						meta: {
							title: '接口角色',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/api/role/edit',
						name: 'SysApiRoleEdit',
						component: () => import('/@/pages/sys/api/role/edit.vue'),
						meta: {
							title: '角色编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
						},
					},
				],
			},
			{
				path: '/sys/portal',
				name: 'SysPortal',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/sys/portal/main',
				meta: {
					title: '门户管理',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Notebook',
				},
				children: [
					{
						path: '/sys/portal/main',
						name: 'SysPortalMain',
						component: () => import('/@/pages/sys/portal/main/index.vue'),
						meta: {
							title: '门户列表',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/portal/main/edit',
						name: 'SysPortalMainEdit',
						component: () => import('/@/pages/sys/portal/main/edit.vue'),
						meta: {
							title: '门户编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/portal/menu',
						name: 'SysPortalMenu',
						component: () => import('/@/pages/sys/portal/menu/index.vue'),
						meta: {
							title: '门户菜单',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/portal/menu/edit',
						name: 'SysPortalMenuEdit',
						component: () => import('/@/pages/sys/portal/menu/edit.vue'),
						meta: {
							title: '菜单编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/portal/role',
						name: 'SysPortalRole',
						component: () => import('/@/pages/sys/portal/role/index.vue'),
						meta: {
							title: '门户角色',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/portal/role/edit',
						name: 'SysPortalRoleEdit',
						component: () => import('/@/pages/sys/portal/role/edit.vue'),
						meta: {
							title: '角色编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
				],
			},
		],
	},
	{
		path: '/mon',
		name: 'Mon',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/mon/server/main',
		meta: {
			title: '监控中心',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin'],
			icon: 'ele-DataLine',
		},
		children: [
			{
				path: '/mon/online/user',
				name: 'MonOnlineUser',
				component: () => import('/@/pages/mon/online/user/index.vue'),
				meta: {
					title: '在线用户',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/mon/log/login',
				name: 'MonLogLogin',
				component: () => import('/@/pages/mon/log/login/index.vue'),
				meta: {
					title: '登录日志',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/mon/log/oper',
				name: 'MonLogOper',
				component: () => import('/@/pages/mon/log/oper/index.vue'),
				meta: {
					title: '操作日志',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/mon/log/error',
				name: 'MonLogError',
				component: () => import('/@/pages/mon/log/error/index.vue'),
				meta: {
					title: '错误日志',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/mon/job/main',
				name: 'MonJobMain',
				component: () => import('/@/pages/mon/job/main/index.vue'),
				meta: {
					title: '定时任务',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/mon/job/main/edit',
				name: 'MonJobMainEdit',
				component: () => import('/@/pages/mon/job/main/edit.vue'),
				meta: {
					title: '定时任务编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
				},
			},
			{
				path: '/mon/job/log',
				name: 'MonJobLog',
				component: () => import('/@/pages/mon/job/log/index.vue'),
				meta: {
					title: '定时任务日志',
					isLink: '',
					isHide: true,
					isKeepAlive: false,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/mon/server/main',
				name: 'MonServerMain',
				component: () => import('/@/pages/mon/server/main/show.vue'),
				meta: {
					title: '服务监控',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/mon/cache/main',
				name: 'MonCacheMain',
				component: () => import('/@/pages/mon/cache/main/show.vue'),
				meta: {
					title: '缓存监控',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/mon/db/main',
				name: 'MonDbMain',
				component: () => import('/@/layout/routerView/link.vue'),
				meta: {
					title: '数据监控',
					isLink: `${import.meta.env.VITE_API_URL}druid/sql.html`,
					isHide: false,
					isKeepAlive: false,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
		],
	},
	{
		path: '/ass',
		name: 'Ass',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/ass/dict/main',
		meta: {
			title: '辅助工具',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin'],
			// icon: 'ele-Help',
			icon: 'ele-Suitcase',
		},
		children: [
			{
				path: '/ass/form/tmpl/edit',
				name: 'AssFormTmplEdit',
				component: () => import('/@/pages/ass/form/tmpl/edit.vue'),
				meta: {
					title: '表单模板配置',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/proc/tmpl/edit',
				name: 'AssProcTmplEdit',
				component: () => import('/@/pages/ass/proc/tmpl/edit.vue'),
				meta: {
					title: '流程模板配置',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/coge/form',
				name: 'AssCogeForm',
				component: () => import('/@/pages/ass/coge/form/index.vue'),
				meta: {
					title: '表单设计',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/coge/form/edit',
				name: 'AssCogeFormEdit',
				component: () => import('/@/pages/ass/coge/form/edit.vue'),
				meta: {
					title: '表单设计维护',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/coge/table',
				name: 'AssCogeTable',
				component: () => import('/@/pages/ass/coge/table/index.vue'),
				meta: {
					title: '代码生成',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/coge/table/edit',
				name: 'AssCogeTableEdit',
				component: () => import('/@/pages/ass/coge/table/edit.vue'),
				meta: {
					title: '代码生成配置',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/dict/main',
				name: 'AssDictMain',
				component: () => import('/@/pages/ass/dict/main/index.vue'),
				meta: {
					title: '数据字典',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/dict/data',
				name: 'AssDictData',
				component: () => import('/@/pages/ass/dict/data/index.vue'),
				meta: {
					title: '字典配置',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/num/main',
				name: 'AssNumMain',
				component: () => import('/@/pages/ass/num/main/index.vue'),
				meta: {
					title: '编号策略',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/oss/main',
				name: 'AssOssMain',
				component: () => import('/@/pages/ass/oss/main/index.vue'),
				meta: {
					title: '文件存储',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/oss/config',
				name: 'AssOssConfg',
				component: () => import('/@/pages/ass/oss/config/index.vue'),
				meta: {
					title: '存储配置',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/addr/main',
				name: 'AssAddrMain',
				component: () => import('/@/pages/ass/addr/main/index.vue'),
				meta: {
					title: '省市区县',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
		],
	},
	{
		path: '/oa',
		name: 'Oa',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/oa/flow/main',
		meta: {
			title: '应用中心',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin'],
			icon: 'ele-Menu',
		},
		children: [
			{
				path: '/oa/flow',
				name: 'OaFlow',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/oa/flow/main',
				meta: {
					title: '流程管理',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Connection',
				},
				children: [
					{
						path: '/oa/flow/cate',
						name: 'OaFlowCate',
						component: () => import('/@/pages/oa/flow/cate/index.vue'),
						meta: {
							title: '流程分类',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/flow/cate/edit',
						name: 'OaFlowCateEdit',
						component: () => import('/@/pages/oa/flow/cate/edit.vue'),
						meta: {
							title: '流程分类编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/flow/tmpl',
						name: 'OaFlowTmpl',
						component: () => import('/@/pages/oa/flow/tmpl/index.vue'),
						meta: {
							title: '流程模板',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/flow/tmpl/edit',
						name: 'OaFlowTmplEdit',
						component: () => import('/@/pages/oa/flow/tmpl/edit.vue'),
						meta: {
							title: '流程模板编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/flow/main',
						name: 'OaFlowMain',
						component: () => import('/@/pages/oa/flow/main/index.vue'),
						meta: {
							title: '流程实例',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/flow/main/view',
						name: 'OaFlowMainView',
						component: () => import('/@/pages/oa/flow/main/view.vue'),
						meta: {
							title: '流程查看',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/flow/main/edit',
						name: 'OaFlowMainEdit',
						component: () => import('/@/pages/oa/flow/main/edit.vue'),
						meta: {
							title: '流程编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/todo/main',
						name: 'SysTodoMain',
						component: () => import('/@/pages/sys/todo/main/index.vue'),
						meta: {
							title: '流程待办',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/todo/main/edit',
						name: 'SysTodoMainEdit',
						component: () => import('/@/pages/sys/todo/main/edit.vue'),
						meta: {
							title: '待办处理',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
				],
			},
		],
	},
	{
		path: '/my',
		name: 'My',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/my/demo/main',
		meta: {
			title: '测试样例',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin'],
			icon: 'ele-GobletSquare',
		},
		children: [
			{
				path: '/my/demo/cate',
				name: 'MyDemoCate',
				component: () => import('/@/pages/my/demo/cate/index.vue'),
				meta: {
					title: 'DEMO分类',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/my/demo/cate/edit',
				name: 'MyDemoCateEdit',
				component: () => import('/@/pages/my/demo/cate/edit.vue'),
				meta: {
					title: 'DEMO分页编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/my/demo/main',
				name: 'MyDemoMain',
				component: () => import('/@/pages/my/demo/main/index.vue'),
				meta: {
					title: 'DEMO清单',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/my/demo/main/edit',
				name: 'MyDemoMainEdit',
				component: () => import('/@/pages/my/demo/main/edit.vue'),
				meta: {
					title: 'DEMO编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/my/demo/main/view',
				name: 'MyDemoMainView',
				component: () => import('/@/pages/my/demo/main/view.vue'),
				meta: {
					title: 'DEMO查看',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/my/demo/main/edit2',
				name: 'MyDemoMainEdit2',
				component: () => import('/@/pages/my/demo/main/edit2.vue'),
				meta: {
					title: 'DEMO编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/my/demo/main/view2',
				name: 'MyDemoMainView2',
				component: () => import('/@/pages/my/demo/main/view2.vue'),
				meta: {
					title: 'DEMO查看',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
		],
	},

];

