import { RouteRecordRaw } from 'vue-router';

export const sysRoutes: Array<RouteRecordRaw> = [
	{
		path: '/sys',
		name: 'Sys',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/sys/org/user',
		meta: {
			title: '系统管理',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin', 'common'],
			icon: 'ele-Setting',
		},
		children: [
			{
				path: '/sys/org',
				name: 'SysOrg',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/sys/org/user',
				meta: {
					title: '组织架构',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin', 'common'],
					icon: 'ele-OfficeBuilding',
				},
				children: [
					{
						path: '/sys/org/dept',
						name: 'SysOrgDept',
						component: () => import('/@/pages/sys/org/dept/index.vue'),
						meta: {
							title: '部门管理',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin', 'common'],
							icon: 'ele-SetUp',
						},
					},
					{
						path: '/sys/org/dept/tindex',
						name: 'SysOrgDeptTindex',
						component: () => import('/@/pages/sys/org/dept/tindex.vue'),
						meta: {
							title: '部门管理',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin', 'common'],
							icon: 'ele-SetUp',
						},
					},
					{
						path: '/sys/org/dept/edit',
						name: 'SysOrgDeptEdit',
						component: () => import('/@/pages/sys/org/dept/edit.vue'),
						meta: {
							title: '部门编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/org/user',
						name: 'SysOrgUser',
						component: () => import('/@/pages/sys/org/user/index.vue'),
						meta: {
							title: '用户管理',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-User',
						},
					},
					{
						path: '/sys/org/user/edit',
						name: 'SysOrgUserEdit',
						component: () => import('/@/pages/sys/org/user/edit.vue'),
						meta: {
							title: '用户编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/org/post',
						name: 'SysOrgPost',
						component: () => import('/@/pages/sys/org/post/index.vue'),
						meta: {
							title: '岗位管理',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Help',
						},
					},
					{
						path: '/sys/org/post/edit',
						name: 'SysOrgPostEdit',
						component: () => import('/@/pages/sys/org/post/edit.vue'),
						meta: {
							title: '岗位编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/org/group',
						name: 'SysOrgGroup',
						component: () => import('/@/pages/sys/org/group/index.vue'),
						meta: {
							title: '群组管理',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Guide',
						},
					},
					{
						path: '/sys/org/group/edit',
						name: 'SysOrgGroupEdit',
						component: () => import('/@/pages/sys/org/group/edit.vue'),
						meta: {
							title: '群组编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/org/rtree',
						name: 'SysOrgRtree',
						component: () => import('/@/pages/sys/org/role/tree.vue'),
						meta: {
							title: '角色管理',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Cherry',
						},
					},
					{
						path: '/sys/org/rtree/edit',
						name: 'SysOrgRtreeEdit',
						component: () => import('/@/pages/sys/org/role/tree_edit.vue'),
						meta: {
							title: '角色树编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/org/rnode',
						name: 'SysOrgRnode',
						component: () => import('/@/pages/sys/org/role/node.vue'),
						meta: {
							title: '角色节点配置',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
				],
			},
			{
				path: '/sys/coop',
				name: 'SysCoop',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/sys/coop/user',
				meta: {
					title: '外部协同',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin', 'common'],
					icon: 'ele-Magnet',
				},
				children: [
					{
						path: '/sys/coop/cate',
						name: 'SysCoopCate',
						component: () => import('/@/pages/sys/coop/cate/index.vue'),
						meta: {
							title: '协同分类',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/coop/corp',
						name: 'SysCoopCorp',
						component: () => import('/@/pages/sys/coop/corp/index.vue'),
						meta: {
							title: '外部公司',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/coop/user',
						name: 'SysCoopUser',
						component: () => import('/@/pages/sys/coop/user/index.vue'),
						meta: {
							title: '外部用户',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
				],
			},

			{
				path: '/sys/api',
				name: 'SysApi',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/sys/api/main',
				meta: {
					title: '接口管理',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Lock',
				},
				children: [
					{
						path: '/sys/api/main',
						name: 'SysApiMain',
						component: () => import('/@/pages/sys/api/main/index.vue'),
						meta: {
							title: '接口清单',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/api/main/doc',
						name: 'SysApiMainDoc',
						component: () => import('/@/layout/routerView/link.vue'),
						meta: {
							title: '接口文档',
							isLink: `${import.meta.env.VITE_API_URL}doc.html`,
							isHide: false,
							isKeepAlive: false,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'iconfont icon-caozuo-wailian',
						},
					},
					{
						path: '/sys/api/role',
						name: 'SysApiRole',
						component: () => import('/@/pages/sys/api/role/index.vue'),
						meta: {
							title: '接口角色',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/api/role/edit',
						name: 'SysApiRoleEdit',
						component: () => import('/@/pages/sys/api/role/edit.vue'),
						meta: {
							title: '角色编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
						},
					},
				],
			},
			{
				path: '/sys/portal',
				name: 'SysPortal',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/sys/portal/main',
				meta: {
					title: '门户管理',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Notebook',
				},
				children: [
					{
						path: '/sys/portal/main',
						name: 'SysPortalMain',
						component: () => import('/@/pages/sys/portal/main/index.vue'),
						meta: {
							title: '门户列表',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/portal/main/edit',
						name: 'SysPortalMainEdit',
						component: () => import('/@/pages/sys/portal/main/edit.vue'),
						meta: {
							title: '门户编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/portal/menu',
						name: 'SysPortalMenu',
						component: () => import('/@/pages/sys/portal/menu/index.vue'),
						meta: {
							title: '门户菜单',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/portal/menu/edit',
						name: 'SysPortalMenuEdit',
						component: () => import('/@/pages/sys/portal/menu/edit.vue'),
						meta: {
							title: '菜单编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/portal/role',
						name: 'SysPortalRole',
						component: () => import('/@/pages/sys/portal/role/index.vue'),
						meta: {
							title: '门户角色',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/portal/role/edit',
						name: 'SysPortalRoleEdit',
						component: () => import('/@/pages/sys/portal/role/edit.vue'),
						meta: {
							title: '角色编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
				],
			},
		],
	},
	{
		path: '/mon',
		name: 'Mon',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/mon/server/main',
		meta: {
			title: '监控中心',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin'],
			icon: 'ele-DataLine',
		},
		children: [
			{
				path: '/mon/online/user',
				name: 'MonOnlineUser',
				component: () => import('/@/pages/mon/online/user/index.vue'),
				meta: {
					title: '在线用户',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/mon/log/login',
				name: 'MonLogLogin',
				component: () => import('/@/pages/mon/log/login/index.vue'),
				meta: {
					title: '登录日志',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/mon/log/oper',
				name: 'MonLogOper',
				component: () => import('/@/pages/mon/log/oper/index.vue'),
				meta: {
					title: '操作日志',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/mon/log/error',
				name: 'MonLogError',
				component: () => import('/@/pages/mon/log/error/index.vue'),
				meta: {
					title: '错误日志',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/mon/job/main',
				name: 'MonJobMain',
				component: () => import('/@/pages/mon/job/main/index.vue'),
				meta: {
					title: '定时任务',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/mon/job/main/edit',
				name: 'MonJobMainEdit',
				component: () => import('/@/pages/mon/job/main/edit.vue'),
				meta: {
					title: '定时任务编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
				},
			},
			{
				path: '/mon/job/log',
				name: 'MonJobLog',
				component: () => import('/@/pages/mon/job/log/index.vue'),
				meta: {
					title: '定时任务日志',
					isLink: '',
					isHide: true,
					isKeepAlive: false,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/mon/server/main',
				name: 'MonServerMain',
				component: () => import('/@/pages/mon/server/main/show.vue'),
				meta: {
					title: '服务监控',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/mon/cache/main',
				name: 'MonCacheMain',
				component: () => import('/@/pages/mon/cache/main/show.vue'),
				meta: {
					title: '缓存监控',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/mon/db/main',
				name: 'MonDbMain',
				component: () => import('/@/layout/routerView/link.vue'),
				meta: {
					title: '数据监控',
					isLink: `${import.meta.env.VITE_API_URL}druid/sql.html`,
					isHide: false,
					isKeepAlive: false,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
		],
	},
	{
		path: '/ass',
		name: 'Ass',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/ass/dict/main',
		meta: {
			title: '辅助工具',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin'],
			// icon: 'ele-Help',
			icon: 'ele-Suitcase',
		},
		children: [
			{
				path: '/ass/form/temp/edit',
				name: 'AssFormTempEdit',
				component: () => import('/@/pages/ass/form/temp/edit.vue'),
				meta: {
					title: '表单模板配置',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/proc/temp/edit',
				name: 'AssProcTempEdit',
				component: () => import('/@/pages/ass/proc/temp/edit.vue'),
				meta: {
					title: '流程模板配置',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/coge/form',
				name: 'AssCogeForm',
				component: () => import('/@/pages/ass/coge/form/index.vue'),
				meta: {
					title: '表单设计',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/coge/form/edit',
				name: 'AssCogeFormEdit',
				component: () => import('/@/pages/ass/coge/form/edit.vue'),
				meta: {
					title: '表单设计维护',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/coge/table',
				name: 'AssCogeTable',
				component: () => import('/@/pages/ass/coge/table/index.vue'),
				meta: {
					title: '代码生成',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/coge/table/edit',
				name: 'AssCogeTableEdit',
				component: () => import('/@/pages/ass/coge/table/edit.vue'),
				meta: {
					title: '代码生成配置',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/dict/main',
				name: 'AssDictMain',
				component: () => import('/@/pages/ass/dict/main/index.vue'),
				meta: {
					title: '数据字典',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/dict/data',
				name: 'AssDictData',
				component: () => import('/@/pages/ass/dict/data/index.vue'),
				meta: {
					title: '字典配置',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/num/main',
				name: 'AssNumMain',
				component: () => import('/@/pages/ass/num/main/index.vue'),
				meta: {
					title: '编号策略',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/oss/main',
				name: 'AssOssMain',
				component: () => import('/@/pages/ass/oss/main/index.vue'),
				meta: {
					title: '文件存储',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/oss/config',
				name: 'AssOssConfg',
				component: () => import('/@/pages/ass/oss/config/index.vue'),
				meta: {
					title: '存储配置',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/ass/addr/main',
				name: 'AssAddrMain',
				component: () => import('/@/pages/ass/addr/main/index.vue'),
				meta: {
					title: '省市区县',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
		],
	},
	// {
	// 	path: '/ic',
	// 	name: 'Ic',
	// 	component: () => import('/@/layout/routerView/parent.vue'),
	// 	redirect: '/dd/org/dept',
	// 	meta: {
	// 		title: '集成中心',
	// 		isLink: '',
	// 		isHide: false,
	// 		isKeepAlive: true,
	// 		isAffix: false,
	// 		isIframe: false,
	// 		roles: ['admin'],
	// 		icon: 'ele-Sunrise',
	// 	},
	// 	children: [
	// 		{
	// 			path: '/ic/dd',
	// 			name: 'IcDd',
	// 			component: () => import('/@/layout/routerView/parent.vue'),
	// 			redirect: '/dd/org/dept',
	// 			meta: {
	// 				title: '钉钉集成',
	// 				isLink: '',
	// 				isHide: false,
	// 				isKeepAlive: true,
	// 				isAffix: false,
	// 				isIframe: false,
	// 				roles: ['admin'],
	// 				icon: 'ele-Connection',
	// 			},
	// 			children: [
	// 				{
	// 					path: '/dd/org/dept',
	// 					name: 'DdOrgDept',
	// 					component: () => import('/@/pages/dd/org/dept/index.vue'),
	// 					meta: {
	// 						title: '部门对照',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/dd/org/user',
	// 					name: 'DdOrgUser',
	// 					component: () => import('/@/pages/dd/org/user/index.vue'),
	// 					meta: {
	// 						title: '用户对照',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 			],
	// 		},
	// 		{
	// 			path: '/si/ekp',
	// 			name: 'SiEkp',
	// 			component: () => import('/@/layout/routerView/parent.vue'),
	// 			redirect: '/si/ekp/org',
	// 			meta: {
	// 				title: '蓝凌集成',
	// 				isLink: '',
	// 				isHide: false,
	// 				isKeepAlive: true,
	// 				isAffix: false,
	// 				isIframe: false,
	// 				roles: ['admin'],
	// 				icon: 'ele-Connection',
	// 			},
	// 			children: [
	// 				{
	// 					path: '/si/ekp/org',
	// 					name: 'SiEkpOrg',
	// 					component: () => import('/@/pages/si/ekp/org/index.vue'),
	// 					meta: {
	// 						title: '组织架构',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 			],
	// 		},
	// 	],
	// },
	{
		path: '/oa',
		name: 'Oa',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/oa/flow/main',
		meta: {
			title: '应用中心',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin'],
			icon: 'ele-Menu',
		},
		children: [
			{
				path: '/oa/flow',
				name: 'OaFlow',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/oa/flow/main',
				meta: {
					title: '流程管理',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Connection',
				},
				children: [
					{
						path: '/oa/flow/cate',
						name: 'OaFlowCate',
						component: () => import('/@/pages/oa/flow/cate/index.vue'),
						meta: {
							title: '流程分类',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/flow/cate/edit',
						name: 'OaFlowCateEdit',
						component: () => import('/@/pages/oa/flow/cate/edit.vue'),
						meta: {
							title: '流程分类编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/flow/temp',
						name: 'OaFlowTemp',
						component: () => import('/@/pages/oa/flow/temp/index.vue'),
						meta: {
							title: '流程模板',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/flow/temp/edit',
						name: 'OaFlowTempEdit',
						component: () => import('/@/pages/oa/flow/temp/edit.vue'),
						meta: {
							title: '流程模板编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/flow/main',
						name: 'OaFlowMain',
						component: () => import('/@/pages/oa/flow/main/index.vue'),
						meta: {
							title: '流程实例',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/flow/main/view',
						name: 'OaFlowMainView',
						component: () => import('/@/pages/oa/flow/main/view.vue'),
						meta: {
							title: '流程查看',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/flow/main/edit',
						name: 'OaFlowMainEdit',
						component: () => import('/@/pages/oa/flow/main/edit.vue'),
						meta: {
							title: '流程编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/todo/main',
						name: 'SysTodoMain',
						component: () => import('/@/pages/sys/todo/main/index.vue'),
						meta: {
							title: '流程待办',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/sys/todo/main/edit',
						name: 'SysTodoMainEdit',
						component: () => import('/@/pages/sys/todo/main/edit.vue'),
						meta: {
							title: '待办处理',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
				],
			},
			{
				path: '/oa/proj',
				name: 'OaProj',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/oa/proj/main',
				meta: {
					title: '项目管理',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Stopwatch',
				},
				children: [
					{
						path: '/oa/proj/main',
						name: 'OaProjMain',
						component: () => import('/@/pages/oa/proj/main/index.vue'),
						meta: {
							title: '项目清单',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/proj/main/view',
						name: 'OaProjMainView',
						component: () => import('/@/pages/oa/proj/main/view.vue'),
						meta: {
							title: '项目查看',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/proj/main/edit',
						name: 'OaProjMainEdit',
						component: () => import('/@/pages/oa/proj/main/edit.vue'),
						meta: {
							title: '项目编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/proj/task',
						name: 'OaProjTask',
						component: () => import('/@/pages/oa/proj/task/index.vue'),
						meta: {
							title: '项目任务',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/proj/task/edit',
						name: 'OaProjTaskEdit',
						component: () => import('/@/pages/oa/proj/task/edit.vue'),
						meta: {
							title: '任务编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
				],
			},
			{
				path: '/oa/task',
				name: 'OaTask',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/oa/task/main',
				meta: {
					title: '任务管理',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Location',
				},
				children: [
					{
						path: '/oa/task/main',
						name: 'OaTaskMain',
						component: () => import('/@/pages/oa/task/main/index.vue'),
						meta: {
							title: '任务清单',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/oa/task/board',
						name: 'OaTaskBoard',
						component: () => import('/@/pages/oa/task/board/index.vue'),
						meta: {
							title: '任务看板',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
				],
			},
		],
	},
	// {
	// 	path: '/bi',
	// 	name: 'Bi',
	// 	component: () => import('/@/layout/routerView/parent.vue'),
	// 	redirect: '/bi/report/main',
	// 	meta: {
	// 		title: '数据分析',
	// 		isLink: '',
	// 		isHide: false,
	// 		isKeepAlive: true,
	// 		isAffix: false,
	// 		isIframe: false,
	// 		roles: ['admin'],
	// 		icon: 'ele-DataLine',
	// 	},
	// 	children: [
	// 		{
	// 			path: '/bi/global',
	// 			name: 'BiGlobal',
	// 			component: () => import('/@/layout/routerView/parent.vue'),
	// 			redirect: '/it/global/mod',
	// 			meta: {
	// 				title: '全局配置',
	// 				isLink: '',
	// 				isHide: false,
	// 				isKeepAlive: true,
	// 				isAffix: false,
	// 				isIframe: false,
	// 				roles: ['admin'],
	// 				icon: 'ele-Postcard',
	// 			},
	// 			children: [
	// 				{
	// 					path: '/bi/global/mod',
	// 					name: 'BiGlobalMod',
	// 					component: () => import('/@/pages/bi/global/mod/index.vue'),
	// 					meta: {
	// 						title: '业务模块',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/bi/global/mod/edit',
	// 					name: 'BiGlobalModEdit',
	// 					component: () => import('/@/pages/bi/global/mod/edit.vue'),
	// 					meta: {
	// 						title: '业务模块编辑',
	// 						isLink: '',
	// 						isHide: true,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 			],
	// 		},
	// 		{
	// 			path: '/bi/collect',
	// 			name: 'BiCollect',
	// 			component: () => import('/@/layout/routerView/parent.vue'),
	// 			redirect: '/it/collect/conn',
	// 			meta: {
	// 				title: '数据采集',
	// 				isLink: '',
	// 				isHide: false,
	// 				isKeepAlive: true,
	// 				isAffix: false,
	// 				isIframe: false,
	// 				roles: ['admin'],
	// 				icon: 'ele-Postcard',
	// 			},
	// 			children: [
	// 				{
	// 					path: '/bi/collect/conn',
	// 					name: 'BiCollectConn',
	// 					component: () => import('/@/pages/bi/collect/conn/index.vue'),
	// 					meta: {
	// 						title: '连接配置',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/bi/collect/data',
	// 					name: 'BiCollectData',
	// 					component: () => import('/@/pages/bi/collect/data/index.vue'),
	// 					meta: {
	// 						title: '原始数据',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/bi/collect/mon',
	// 					name: 'BiCollectMon',
	// 					component: () => import('/@/layout/routerView/iframes.vue'),
	// 					meta: {
	// 						title: '数据监控',
	// 						isLink: `${import.meta.env.VITE_API_URL}druid/datasource.html`,
	// 						isHide: false,
	// 						isKeepAlive: false,
	// 						isAffix: false,
	// 						isIframe: true,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 			],
	// 		},
	// 		{
	// 			path: '/bi/model',
	// 			name: 'BiModel',
	// 			component: () => import('/@/layout/routerView/parent.vue'),
	// 			redirect: '/it/model/map',
	// 			meta: {
	// 				title: '数据建模',
	// 				isLink: '',
	// 				isHide: false,
	// 				isKeepAlive: true,
	// 				isAffix: false,
	// 				isIframe: false,
	// 				roles: ['admin'],
	// 				icon: 'ele-Postcard',
	// 			},
	// 			children: [
	// 				{
	// 					path: '/bi/model/base',
	// 					name: 'BiModelBase',
	// 					component: () => import('/@/pages/bi/model/base/index.vue'),
	// 					meta: {
	// 						title: '模型仓库',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/bi/model/base/edit',
	// 					name: 'BiModelBaseEdit',
	// 					component: () => import('/@/pages/bi/model/base/edit.vue'),
	// 					meta: {
	// 						title: '模型仓库编辑',
	// 						isLink: '',
	// 						isHide: true,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/bi/model/config',
	// 					name: 'BiModelConfig',
	// 					component: () => import('/@/pages/bi/model/config/index.vue'),
	// 					meta: {
	// 						title: '模型仓库配置',
	// 						isLink: '',
	// 						isHide: true,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/bi/model/data',
	// 					name: 'BiModelData',
	// 					component: () => import('/@/pages/bi/model/data/index.vue'),
	// 					meta: {
	// 						title: '模型数据',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/bi/model/map',
	// 					name: 'BiModelMap',
	// 					component: () => import('/@/pages/bi/model/map/index.vue'),
	// 					meta: {
	// 						title: '模型图谱',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/bi/model/map/edit',
	// 					name: 'BiModelMapEdit',
	// 					component: () => import('/@/pages/bi/model/map/edit.vue'),
	// 					meta: {
	// 						title: '模型图谱维护',
	// 						isLink: '',
	// 						isHide: true,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 			],
	// 		},
	// 		{
	// 			path: '/bi/trans',
	// 			name: 'BiTrans',
	// 			component: () => import('/@/layout/routerView/parent.vue'),
	// 			redirect: '/it/trans/main',
	// 			meta: {
	// 				title: '数据转换',
	// 				isLink: '',
	// 				isHide: false,
	// 				isKeepAlive: true,
	// 				isAffix: false,
	// 				isIframe: false,
	// 				roles: ['admin'],
	// 				icon: 'ele-Postcard',
	// 			},
	// 			children: [
	// 				{
	// 					path: '/bi/trans/main',
	// 					name: 'BiTransMain',
	// 					component: () => import('/@/pages/bi/trans/main/index.vue'),
	// 					meta: {
	// 						title: '转换清单',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/bi/trans/main/edit',
	// 					name: 'BiTransMainEdit',
	// 					component: () => import('/@/pages/bi/trans/main/edit.vue'),
	// 					meta: {
	// 						title: '转换编辑',
	// 						isLink: '',
	// 						isHide: true,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/bi/trans/cron',
	// 					name: 'BiTransCron',
	// 					component: () => import('/@/pages/bi/trans/cron/index.vue'),
	// 					meta: {
	// 						title: '转换任务',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/bi/trans/cron/edit',
	// 					name: 'BiTransCronEdit',
	// 					component: () => import('/@/pages/bi/trans/cron/edit.vue'),
	// 					meta: {
	// 						title: '任务编辑',
	// 						isLink: '',
	// 						isHide: true,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/bi/trans/log',
	// 					name: 'BiTransLog',
	// 					component: () => import('/@/pages/bi/trans/log/index.vue'),
	// 					meta: {
	// 						title: '转换日志',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 			],
	// 		},
	// 		{
	// 			path: '/bi/report',
	// 			name: 'BiReport',
	// 			component: () => import('/@/layout/routerView/parent.vue'),
	// 			redirect: '/bi/report/cate',
	// 			meta: {
	// 				title: '数据报表',
	// 				isLink: '',
	// 				isHide: false,
	// 				isKeepAlive: true,
	// 				isAffix: false,
	// 				isIframe: false,
	// 				roles: ['admin'],
	// 				icon: 'ele-Postcard',
	// 			},
	// 			children: [
	// 				{
	// 					path: '/bi/report/cate',
	// 					name: 'BiReportCate',
	// 					component: () => import('/@/pages/bi/report/cate/index.vue'),
	// 					meta: {
	// 						title: '报表分类',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/bi/report/main',
	// 					name: 'BiReportMain',
	// 					component: () => import('/@/pages/bi/report/main/index.vue'),
	// 					meta: {
	// 						title: '报表清单',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/bi/report/main/edit',
	// 					name: 'BiReportMainEdit',
	// 					component: () => import('/@/pages/bi/report/main/edit.vue'),
	// 					meta: {
	// 						title: '报表编辑',
	// 						isLink: '',
	// 						isHide: true,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/bi/report/role',
	// 					name: 'BiReportRole',
	// 					component: () => import('/@/pages/bi/collect/conn/index.vue'),
	// 					meta: {
	// 						title: '报表角色',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 			],
	// 		},
	// 	],
	// },
	// {
	// 	path: '/it',
	// 	name: 'It',
	// 	component: () => import('/@/layout/routerView/parent.vue'),
	// 	redirect: '/it/server/main',
	// 	meta: {
	// 		title: '运维管理',
	// 		isLink: '',
	// 		isHide: false,
	// 		isKeepAlive: true,
	// 		isAffix: false,
	// 		isIframe: false,
	// 		roles: ['admin'],
	// 		icon: 'ele-MostlyCloudy',
	// 	},
	// 	children: [
	// 		{
	// 			path: '/it/server',
	// 			name: 'ItServer',
	// 			component: () => import('/@/layout/routerView/parent.vue'),
	// 			redirect: '/it/server/main',
	// 			meta: {
	// 				title: '服务器管理',
	// 				isLink: '',
	// 				isHide: false,
	// 				isKeepAlive: true,
	// 				isAffix: false,
	// 				isIframe: false,
	// 				roles: ['admin'],
	// 				icon: 'ele-Postcard',
	// 			},
	// 			children: [
	// 				{
	// 					path: '/it/server/cate',
	// 					name: 'ItServerCate',
	// 					component: () => import('/@/pages/it/server/cate/index.vue'),
	// 					meta: {
	// 						title: '服务器分类',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/it/server/cate/edit',
	// 					name: 'ItServerCateEdit',
	// 					component: () => import('/@/pages/it/server/cate/edit.vue'),
	// 					meta: {
	// 						title: '服务器分类编辑',
	// 						isLink: '',
	// 						isHide: true,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/it/server/main',
	// 					name: 'ItServerMain',
	// 					component: () => import('/@/pages/it/server/main/index.vue'),
	// 					meta: {
	// 						title: '服务器清单',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/it/server/main/edit',
	// 					name: 'ItServerMainEdit',
	// 					component: () => import('/@/pages/it/server/main/edit.vue'),
	// 					meta: {
	// 						title: '服务器编辑',
	// 						isLink: '',
	// 						isHide: true,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 			],
	// 		},
	// 		{
	// 			path: '/it/db',
	// 			name: 'ItDb',
	// 			component: () => import('/@/layout/routerView/parent.vue'),
	// 			redirect: '/it/db/main',
	// 			meta: {
	// 				title: '数据库管理',
	// 				isLink: '',
	// 				isHide: false,
	// 				isKeepAlive: true,
	// 				isAffix: false,
	// 				isIframe: false,
	// 				roles: ['admin'],
	// 				icon: 'ele-Postcard',
	// 			},
	// 			children: [
	// 				{
	// 					path: '/it/db/cate',
	// 					name: 'ItDbCate',
	// 					component: () => import('/@/pages/it/db/cate/index.vue'),
	// 					meta: {
	// 						title: '数据库分类',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/it/db/cate/edit',
	// 					name: 'ItDbCateEdit',
	// 					component: () => import('/@/pages/it/db/cate/edit.vue'),
	// 					meta: {
	// 						title: '数据库分类编辑',
	// 						isLink: '',
	// 						isHide: true,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/it/db/main',
	// 					name: 'ItDbMain',
	// 					component: () => import('/@/pages/it/db/main/index.vue'),
	// 					meta: {
	// 						title: '数据库清单',
	// 						isLink: '',
	// 						isHide: false,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 				{
	// 					path: '/it/db/main/edit',
	// 					name: 'ItDbMainEdit',
	// 					component: () => import('/@/pages/it/db/main/edit.vue'),
	// 					meta: {
	// 						title: '数据库编辑',
	// 						isLink: '',
	// 						isHide: true,
	// 						isKeepAlive: true,
	// 						isAffix: false,
	// 						isIframe: false,
	// 						roles: ['admin'],
	// 						icon: 'ele-Tickets',
	// 					},
	// 				},
	// 			],
	// 		},
	// 	],
	// },
	// {
	// 	path: '/sys/todo',
	// 	name: 'SysTodo',
	// 	component: () => import('/@/layout/routerView/parent.vue'),
	// 	redirect: '/sys/todo/main',
	// 	meta: {
	// 		title: '待办管理',
	// 		isLink: '',
	// 		isHide: false,
	// 		isKeepAlive: true,
	// 		isAffix: false,
	// 		isIframe: false,
	// 		roles: ['admin'],
	// 		icon: 'ele-Bell',
	// 	},
	// 	children: [
	// 		{
	// 			path: '/sys/todo/main',
	// 			name: 'SysTodoMain',
	// 			component: () => import('/@/pages/sys/todo/main/index.vue'),
	// 			meta: {
	// 				title: '待办清单',
	// 				isLink: '',
	// 				isHide: false,
	// 				isKeepAlive: true,
	// 				isAffix: false,
	// 				isIframe: false,
	// 				roles: ['admin'],
	// 				icon: 'ele-Tickets',
	// 			},
	// 		},
	// 		{
	// 			path: '/sys/todo/main/edit',
	// 			name: 'SysTodoMainEdit',
	// 			component: () => import('/@/pages/sys/todo/main/edit.vue'),
	// 			meta: {
	// 				title: '待办编辑',
	// 				isLink: '',
	// 				isHide: true,
	// 				isKeepAlive: true,
	// 				isAffix: false,
	// 				isIframe: false,
	// 				roles: ['admin'],
	// 				icon: 'ele-Tickets',
	// 			},
	// 		},
	// 	],
	// },
	{
		path: '/my',
		name: 'My',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/my/demo/main',
		meta: {
			title: '测试样例',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin'],
			icon: 'ele-GobletSquare',
		},
		children: [
			{
				path: '/my/demo/cate',
				name: 'MyDemoCate',
				component: () => import('/@/pages/my/demo/cate/index.vue'),
				meta: {
					title: 'DEMO分类',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/my/demo/cate/edit',
				name: 'MyDemoCateEdit',
				component: () => import('/@/pages/my/demo/cate/edit.vue'),
				meta: {
					title: 'DEMO分页编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/my/demo/main',
				name: 'MyDemoMain',
				component: () => import('/@/pages/my/demo/main/index.vue'),
				meta: {
					title: 'DEMO清单',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/my/demo/main/edit',
				name: 'MyDemoMainEdit',
				component: () => import('/@/pages/my/demo/main/edit.vue'),
				meta: {
					title: 'DEMO编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/my/demo/main/view',
				name: 'MyDemoMainView',
				component: () => import('/@/pages/my/demo/main/view.vue'),
				meta: {
					title: 'DEMO查看',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/my/demo/main/edit2',
				name: 'MyDemoMainEdit2',
				component: () => import('/@/pages/my/demo/main/edit2.vue'),
				meta: {
					title: 'DEMO编辑',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
			{
				path: '/my/demo/main/view2',
				name: 'MyDemoMainView2',
				component: () => import('/@/pages/my/demo/main/view2.vue'),
				meta: {
					title: 'DEMO查看',
					isLink: '',
					isHide: true,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Tickets',
				},
			},
		],
	},

];

