import { RouteRecordRaw } from 'vue-router';

export const teRoutes: Array<RouteRecordRaw> = [
	{
		path: '/te',
		name: 'Te',
		component: () => import('/@/layout/routerView/parent.vue'),
		redirect: '/te/prod/model',
		meta: {
			title: '技术管理',
			isLink: '',
			isHide: false,
			isKeepAlive: true,
			isAffix: false,
			isIframe: false,
			roles: ['admin'],
			icon: 'ele-Menu',
		},
		children: [
			{
				path: '/te/prod',
				name: 'TeProd',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/te/prod/main',
				meta: {
					title: '产品管理',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Postcard',
				},
				children: [
					{
						path: '/te/prod/cate',
						name: 'TeProdCate',
						component: () => import('/@/pages/te/prod/cate/index.vue'),
						meta: {
							title: '产品分类',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/prod/serie',
						name: 'TeProdSerie',
						component: () => import('/@/pages/te/prod/serie/index.vue'),
						meta: {
							title: '产品系列',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/prod/model',
						name: 'TeProdModel',
						component: () => import('/@/pages/te/prod/model/index.vue'),
						meta: {
							title: '产品型号',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/prod/temp',
						name: 'TeProdTemp',
						component: () => import('/@/pages/te/prod/temp/index.vue'),
						meta: {
							title: '产品模板',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/prod/temp/edit',
						name: 'TeProdTempEdit',
						component: () => import('/@/pages/te/prod/temp/edit.vue'),
						meta: {
							title: '产品模板编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/prod/main',
						name: 'TeProdMain',
						component: () => import('/@/pages/te/prod/main/index.vue'),
						meta: {
							title: '产品实例',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/prod/main/edit',
						name: 'TeProdMainEdit',
						component: () => import('/@/pages/te/prod/main/edit.vue'),
						meta: {
							title: '产品编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
				],
			},
			{
				path: '/te/feat',
				name: 'TeFeat',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/te/feat/param',
				meta: {
					title: '特性管理',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Postcard',
				},
				children: [
					{
						path: '/te/feat/screen',
						name: 'TeFeatScreen',
						component: () => import('/@/pages/te/feat/screen/index.vue'),
						meta: {
							title: '特性屏幕',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/feat/param',
						name: 'TeFeatParam',
						component: () => import('/@/pages/te/feat/param/index.vue'),
						meta: {
							title: '特性参数',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/feat/param/edit',
						name: 'TeFeatParamEdit',
						component: () => import('/@/pages/te/feat/param/edit.vue'),
						meta: {
							title: '参数编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Comment',
						},
					},
					{
						path: '/te/feat/link',
						name: 'TeFeatLink',
						component: () => import('/@/pages/te/feat/link/index.vue'),
						meta: {
							title: '特性联动',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/feat/link/edit',
						name: 'TeFeatLinkEdit',
						component: () => import('/@/pages/te/feat/link/edit.vue'),
						meta: {
							title: '联动编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/feat/check',
						name: 'TeFeatCheck',
						component: () => import('/@/pages/te/feat/check/index.vue'),
						meta: {
							title: '特性校验',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/feat/check/edit',
						name: 'TeFeatCheckEdit',
						component: () => import('/@/pages/te/feat/check/edit.vue'),
						meta: {
							title: '校验编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/feat/drive',
						name: 'TeFeatDrive',
						component: () => import('/@/pages/te/feat/drive/index.vue'),
						meta: {
							title: '特性驱动',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/feat/drive/edit',
						name: 'TeFeatDriveEdit',
						component: () => import('/@/pages/te/feat/drive/edit.vue'),
						meta: {
							title: '驱动编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/feat/price',
						name: 'TeFeatPrice',
						component: () => import('/@/pages/te/feat/price/index.vue'),
						meta: {
							title: '特性加价',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/feat/price/edit',
						name: 'TeFeatPriceEdit',
						component: () => import('/@/pages/te/feat/price/edit.vue'),
						meta: {
							title: '加价编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/feat/comp',
						name: 'TeFeatComp',
						component: () => import('/@/pages/te/feat/comp/index.vue'),
						meta: {
							title: '特性组件',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/feat/comp/edit',
						name: 'TeFeatCompEdit',
						component: () => import('/@/pages/te/feat/comp/edit.vue'),
						meta: {
							title: '组件编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
				],
			},
			{
				path: '/te/tranx',
				name: 'TeTranx',
				component: () => import('/@/layout/routerView/parent.vue'),
				redirect: '/te/tranx/main',
				meta: {
					title: '询价转换',
					isLink: '',
					isHide: false,
					isKeepAlive: true,
					isAffix: false,
					isIframe: false,
					roles: ['admin'],
					icon: 'ele-Postcard',
				},
				children: [
					{
						path: '/te/tranx/cate',
						name: 'TeTranxCate',
						component: () => import('/@/pages/te/tranx/cate/index.vue'),
						meta: {
							title: '询价分类',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/tranx/model',
						name: 'TeTranxModel',
						component: () => import('/@/pages/te/tranx/model/index.vue'),
						meta: {
							title: '询价型号',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/tranx/screen',
						name: 'TeTranxScreen',
						component: () => import('/@/pages/te/tranx/screen/index.vue'),
						meta: {
							title: '询价屏幕',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/tranx/param',
						name: 'TeTranxParam',
						component: () => import('/@/pages/te/tranx/param/index.vue'),
						meta: {
							title: '询价参数',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/tranx/param/edit',
						name: 'TeTranxParamEdit',
						component: () => import('/@/pages/te/tranx/param/edit.vue'),
						meta: {
							title: '询价参数编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/tranx/rule',
						name: 'TeTranxRule',
						component: () => import('/@/pages/te/tranx/rule/index.vue'),
						meta: {
							title: '转换规则',
							isLink: '',
							isHide: false,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
					{
						path: '/te/tranx/rule/edit',
						name: 'TeTranxRuleEdit',
						component: () => import('/@/pages/te/tranx/rule/edit.vue'),
						meta: {
							title: '转换规则编辑',
							isLink: '',
							isHide: true,
							isKeepAlive: true,
							isAffix: false,
							isIframe: false,
							roles: ['admin'],
							icon: 'ele-Tickets',
						},
					},
				]
			},
		],
	},
];

